# Generated by Django 4.2.5 on 2023-09-26 21:26

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "patientId",
                    models.CharField(
                        max_length=100,
                        primary_key=True,
                        serialize=False,
                        verbose_name="病历ID",
                    ),
                ),
                ("patientName", models.CharField(max_length=100, verbose_name="姓名")),
                (
                    "diseaseKind",
                    models.CharField(default="", max_length=100, verbose_name="病种"),
                ),
                ("videoUrl", models.URLField(verbose_name="视频url")),
                (
                    "createTime",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                ("faceUrlSelf", models.URLField(default="", verbose_name="面象照片url")),
                ("faceUrlStd", models.URLField(default="", verbose_name="基准面象照片url")),
                ("tongueUrlSelf", models.URLField(default="", verbose_name="舌象照片url")),
                ("tongueUrlStd", models.URLField(default="", verbose_name="基准舌象照片url")),
            ],
        ),
    ]
